### ISSUE TITLE
UVBrick won't compile with casacore 2

### ISSUE THREAD

**Issue by twillis449** [ska-sa/meqtrees-timba#22]
Unfortunately the code images/Images/ImageFFT seems to have  disappeared from casacore 2. The UV Brick calls some functions from ImageFFT so it currently will not compile with casacore 2.

**Comment by ludwigschwardt** [comment]
Yes,

Casacore got more "core" in the latest release. The whole of Components
also vanished...

Regards,

Ludwig

**Comment by o-smirnov** [comment]
Hmmm, if it's only the one ImageFFT class that's gone missing, could we
just absorb it into the Timba codebase?

**Comment by twillis449** [comment]
I suspect that would be the easiest solution.  Or maybe just copy over the needed functions and integrate them into the UVBrick. (The UVBrick only calls three ImageFFT functions, but these functions do call some other ImageFFT functions.)

**Comment by gijzelaerr** [comment]
or complain and wait a bit more upstream. I believe some things have been removed or moved to CASA since they where too telescope specific. I don't have the knowledge to judge if that was a fair decision. Maybe this should be reintroduced in 2.1.

**Comment by twillis449** [comment]
Well, I have complained in the casacore 'Issues' list https://github.com/casacore/casacore/issues/123 so I guess we'll see what happens. :)

**Comment by twillis449** [comment]
Unfortunately my experience with casa-related issues is that unless one finds a bug specifically related to the VLA or ALMA one can wait a long time before something gets done. :(

**Comment by twillis449** [comment]
I see why this stuff disappeared. A search through the source code for casacore 1.7 and casarest shows that objects from this class are not used anywhere! There is an include call for ImageFFT,h in casarest//synthesis/MeasurementComponents/ALMAAperture.h but its not used anywhere in casarest//synthesis/MeasurementComponents/ALMAAperture.cc so compilation still completes after commenting out the include statement.

**Comment by twillis449** [comment]
Or maybe not. I downloaded the latest casarest, which is compatible with casacore 2. The ImageFFT code is now in directory casarest/synthesis/Images. It also appears to now be used in a piece of code called ImagePolarimetry. So I guess the modification that would need to be done is to require installation of casarest in addition to casacore, and modify the linking requirements in the MeqTrees build.

**Comment by gijzelaerr** [comment]
I can confirm installing casarest will solve this problem:

https://github.com/casacore/casarest/releases/tag/v1.3.0

**Comment by gijzelaerr** [comment]
actually, almost...

**Comment by gijzelaerr** [comment]
@twillis449 Trying to fix this. We moved casarest to here:

https://github.com/casacore/casarest/tree/master/synthesis/Images

Problem one is that the synthesis/Images headers are not installed, fixing that.

Second problem is if you are right @twillis449 the header structure changed also. In  `MeqNodes/src/UVBrick.cc`:
```
#include <images/Images/ImageInterface.h
#include <images/Images/PagedImage.h>
#include <images/Images/ImageFFT.h>
#include <images/Images/TempImage.h>
```

while the `synthesis/Images` contains:

```
ImageFFT.h
ImageMetaData.h
ImagePolarimetry.h
```

**Comment by gijzelaerr** [comment]
ok should be solved now. You need to install casarest 1.3.1: https://github.com/casacore/casarest/releases/tag/v1.3.1

And build meqtrees from the master. Will make a new release and update the packages.

**Comment by twillis449** [comment]
@gijzelaerr  Thanks for working on this!

I downloaded latest casacore - seems to compile and install OK. I then downloaded casarest 1.3.1 source code gz file, did mkdir build, cd build, cmake .. , but right away I get one of those horrendous bazillion line c++ error messages which seems to come down to 

[NRC-005592LX 9:29am] [build]> make
[  1%] Building CXX object components/CMakeFiles/casa_components.dir/SpectralComponents/CompiledSpectralElement.cc.o

blah blah blah

/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc: In member function ‘const casa::String& casa::CompiledSpectralElement::getFunction() const’:
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:107:58: error: ‘_getFunction’ was not declared in this scope
  CountedPtr<Function<Double, Double> >  f = _getFunction();
                                                          ^
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:108:50: error: ‘_getFunction’ is not a member of ‘casa::SpectralElement’
  return dynamic_cast<CompiledFunction<Double> *>(SpectralElement::_getFunction().get())->getText();
                                                  ^
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc: In member function ‘virtual void casa::CompiledSpectralElement::_setFunction(const casa::String&)’:
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:114:57: error: ‘_getFunction’ was not declared in this scope
  CountedPtr<Function<Double, Double> > f = _getFunction();
                                                         ^
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:134:2: error: ‘_setFunction’ is not a member of ‘casa::SpectralElement’
  SpectralElement::_setFunction(f);
  ^
make[2]: *** [components/CMakeFiles/casa_components.dir/SpectralComponents/CompiledSpectralElement.cc.o] Error 1
make[1]: *** [components/CMakeFiles/casa_components.dir/all] Error 2

**Comment by gijzelaerr** [comment]
this is an issue with casarest, moved here:

https://github.com/casacore/casarest/issues/1

**Comment by twillis449** [comment]
Looks like the new meqtrees build goes to completion after I got the new casarest to build. :)
