### ISSUE TITLE
It may be better to use python2 explicitly

### ISSUE THREAD

**Issue by astrojhgu** [ska-sa/meqtrees-timba#28]
On some systems, which has both python2 and python3, some meqtrees python scripts cannot run sucessfully. The reason is that these scripts are written in python2, while the first lines are "#!/usr/bin/python" or "#!/usr/bin/env python", which will point to python3.

**Comment by gijzelaerr** [comment]
is this on a ubuntu 16.04 system?

probably ```#!/usr/bin/env python2``` is best then.

**Comment by astrojhgu** [comment]
Actually, my system is Archlinux, on which 
ls -lh /usr/bin/python
/usr/bin/python -> python3
