### ISSUE TITLE
What happened to QWhatsThis?

### ISSUE THREAD

**Issue by twillis449** [ska-sa/meqtrees-timba#31]
At one time we had access to the QWhatsThis feature and I used this to provide instructions on how to control aspects of the plotting widgets. Unfortunately displaying this option seems to have disappeared although Qt still seems to provide a QWhatsThis widget. I just wasted a couple of days trying to figure out how my N-Dimensional controller works and finally I had to resort to reading the instructions in the python code!

**Comment by o-smirnov** [comment]
Github's wonderful code search tools tell me it got commented out here: https://github.com/ska-sa/meqtrees-timba/commit/341ce9172c69d970085e4e426ee7690cb4ee7eaf

Don't remember the exact motivation anymore, but I suppose I did that to unclutter the toolbar. It's still there in the Help menu (and accessible as Shift+F1).

**Comment by twillis449** [comment]
Thanks for pointing out that shift+f1 works in the help drop-down menu. I'm re-opening the issue because when one does a shift+f1 the WhatsThis panel does appear but there's no text! I think this is my bad somewhere because when I run one of my plugins in stand-alone test mode, the same behaviour appears.  So I'm investigating further.

**Comment by twillis449** [comment]
It looks like this may be a PyQt or PyQwt bug. A lot of the PyQwt examples have WhatsThis function calls and just like my stuff a WhatThis window pops up, but without text. I'll try to strip out PyQwt calls in one of the demos and see what happens with a pure PyQt script

**Comment by twillis449** [comment]
It would appear that this issue may have some OS dependencies. On 'standard' ubuntu 14.04 and 16.04 with PyQt4 v 4.10 and 4.11 respectively the WhatsThis screen pops up but no text appears.  However , on Xubuntu 14.04 which also has PyQt4 v 4.10, it works.

I'm attaching the most basic script possible to test this issue. Just start it up with your python and hit shift + f1.  It things are working, text will appear in a popup window. Otherwise you get the popup window, but sadly, no text.

[WhatsThis_test.txt](https://github.com/ska-sa/meqtrees-timba/files/426346/WhatsThis_test.txt)

**Comment by twillis449** [comment]
It looks like this problem is associated with some combination of the terminals / desktop environment that  comes with the ubuntu 'gnome-session-fallback' or 'gnome-session-flashback' packages.
