### ISSUE TITLE
meqserver falls over trying to insert new MS column on 16.04

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/meqtrees-timba#35]
This is a new development, possibly related to new casacore versions. The current batch_test.py in Cattery falls over when the meqserver tries to insert a new visibilities column. Backtrace shows it deep in casacore. Could be a casacore bug, could be a MeqTrees misuse. In any case it's a blocker that needs to be solved.

**Comment by gijzelaerr** [comment]
This has been isolated and was caused by an update to the casacore package, but meqtrees-timba was not rebuild.

**Comment by gijzelaerr** [comment]
this has been solved by a rebuild of timba in kern-dev and kern-2
