### ISSUE TITLE
meqtrees-timba does not compile under gcc 6.2.0

### ISSUE THREAD

**Issue by adrianjhpc** [ska-sa/meqtrees-timba#43]
There are a couple of files that cause compilation problems with gcc 6.2.0. Specifically they produce errors like this:
TFSmearFactor.cc:75:24: error: call of overloaded ‘abs(double)’ is ambiguous
     if( abs(freq0-freq1)/midfreq < narrow_band_limit_ )

This can be fixed by adding the cmath headers in to the files in question:

meqtrees-timba/MeqNodes/src/PSVTensor.cc
meqtrees-timba/MeqNodes/src/TFSmearFactor.cc

**Comment by adrianjhpc** [comment]
If you give me commit permissions for the repo I can create a pull request for a fix for this.

**Comment by gijzelaerr** [comment]
hi @adrianjhpc , you don't need commit access to issue a PR. you can fork the repo (up right), commit to a branch on that repo and then issue a PR from your fork to the main repo.
