### ISSUE TITLE
turbo-sim.py skymodel issues

### ISSUE THREAD

**Issue by twillis449** [ska-sa/meqtrees-timba#47]
First @o-smirnov and @gijzelaerr  thanks for porting MeqTrees into the KERN environment - that must have been a Herculean task! 

Thinks seem to be working for me with the exception that the venerable turbo-sim.py script seems have an issue. When I want to specify a skymodel, the tigger-lsm option works. But if I want to specify a skymodel such as Siamese.OMS.gridded-sky, etc. nothing happens when I check the appropriate box. No submenu for specifying parameters such as shape etc appears. There's absolutely no response whatsoever, not even an error message on the command-line terminal saying that the Siamese modules cannot be found etc. 

I'm running Ubunu 18.04

**Comment by gijzelaerr** [comment]
hm... i can't really help you since I have no idea what is supposed to happen. @o-smirnov ?

**Comment by twillis449** [comment]
Totally weird - this morning (for me) its working properly. Maybe there was some quantum mechanical fluctuation in the cosmos yesterday.

**Comment by o-smirnov** [comment]
We used to blame cosmic rays for these things! Glad it works --reopen the issue if you spot it again.

**Comment by twillis449** [comment]
Well, I can see what's happening - not sure why but ... When I tried running the current turbo-sim.py yesterday it was from a somewhat ancient directory with a whole bunch of other rather ancient TDL scripts. Something there is confusing the current turbo-sim.py because when I run from a completely fresh directory with no other TDL scripts, everything works OK. So, anyway, probably not work pursuing further.

**Comment by twillis449** [comment]
I'm going to re-open this issue for a slightly different reason. I can now indeed select any of the skymodel types. But using the tigger-lsm model by itself in turbo-sim.py seems to fail (most) of  the time with  errors of the form: node 'sink:10:11': shape of child result does not match output column (while getting result for request ev.0.0.0.0.1)  and nothing gets written out to the MS. However if I also select one of the gridded skymodels in addition to the tigger-lsm then everything works!

**Comment by o-smirnov** [comment]
Is your lsm a point source at phase centre per chance? There's the old
problem that it never handled the lack of a frequency axis gracefully....

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by twillis449** [comment]
!@#$%^ damn - I'd forgotten about that.  :(  I've been banging my head against the wall for about three days with this problem - trying MeqTrees installs on different machines etc.  But you handle a gridded sky cross model with only one source in each direction (so at the field centre)  absolutely perfectly. I would have thought that deep in the system you must end up handling things the same way? Or not?

**Comment by o-smirnov** [comment]
I think I added some tiny number to the lm in the gridded models to get
around this problem...

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by twillis449** [comment]
aarggghhh!!  :)
