### ISSUE TITLE
baseline  visibility visualization doesn't work in current KERN version

### ISSUE THREAD

**Issue by twillis449** [ska-sa/meqtrees-timba#48]
It's apparent that nobody uses the MeqTrees visualization stuff to look at individual visibilities! If you do you get the error
  File "/usr/lib/python2.7/dist-packages/Timba/Plugins/display_image_qt4.py", line 3325, in array_plot
    temp_str1 = "sd: %-.3g" % plot_array.std(dtype=numpy.complex128);
TypeError: float argument required, not MeqVells

I've unfortunately forgotten some of the deeper cosmic meanings of MeqVells but you can get rid of the error by getting rid of the dtype specification ie. 
temp_str1 = "sd: %-.3g" % plot_array.std()  seems to work OK.

**Comment by bennahugo** [comment]
@twillis449 was this part of your fixes?

**Comment by twillis449** [comment]
Yes, that should have been fixed in the Qt5 version of the code that I checked in.

**Comment by bennahugo** [comment]
Thanks then I'm closing this ticket.
