### ISSUE TITLE
make work with blitz++ 0.10

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/meqtrees-timba#9]
it looks like the API changed for blitz++ 0.10

http://upstream-tracker.org/versions/blitz.html
https://github.com/ska-sa/meqtrees-timba-debian/issues/4
https://launchpadlibrarian.net/171786536/buildlog_ubuntu-trusty-amd64.meqtrees-timba_1.3.1-1trusty_FAILEDTOBUILD.txt.gz

**Comment by o-smirnov** [comment]
...though I fear moving to blitz 0.10 may be even uglier. *Whatever happened to backwards compatibility, mofos?*

**Comment by gijzelaerr** [comment]
Folkert is working on that now

Op vr 9 jan. 2015 15:46 schreef Oleg Smirnov <notifications@github.com>:

**Comment by gijzelaerr** [comment]
https://github.com/ska-sa/meqtrees-timba/pull/15

**Comment by o-smirnov** [comment]
Haha, that was quick. I stand duly shamed. :)

**Comment by gijzelaerr** [comment]
fixed

https://github.com/ska-sa/meqtrees-timba/commit/74daf5a7a9fa03b4fd8c325a5cd3c8f052900a54
